agent.client.list=local
convert.old.scenarios=true
htmlReportDir=log
jsystem.level=INFO
logger=true
max.building.blocks.number=5000
data.provider.classes=jsystem.framework.scenario.flow_control.datadriven.CsvDataProvider
reporter.classes=jsystem.extensions.report.simpleHtmlReporter.SimpleHtmlReporter
resources.src=projects/jsystemServices/src/main/resources
sutClassName=jsystem.framework.sut.SutImpl
sutFile=mystation.xml
tests.dir=projects/jsystemServices/target/classes
tests.src=projects/jsystemServices/src/main/java
